### ISSUE TITLE
Course logic

### ISSUE THREAD

**Issue by miler350** [UviiApp/Uvii#5]
**Background:**

We want to add the ability to share videos, surveys, questions, etc. to pre-identified user groups.

**Summary:**

We want to add a "course" object to the admin panel and give that object the ability to interact with schools, instructors, and students.

**Tasks:**

- [ ] Add course object to admin panel -> admin should be able add, edit, and delete courses.
- [ ] Courses should belong to (are children) of the school object.
- [ ] If schools are removed, the courses should be removed as well.
- [ ] For now, course object only needs :name attribute in the db table.
- [ ] Each course will have 1 instructor (that leads the course).
- [ ] Each course can have many students.
- [ ] An instructor can have many courses.
- [ ] A student can have many courses.
- [ ] The school/admin relationship will be set in admin panel.
- [ ] The course/instructor relationship will be set in admin panel.
- [ ] The course/student will be set in app -> flow is below:
- [ ] -> Student creates account
- [ ] -> Student selects school
- [ ] -> Student selects courses they belong to for that school
- [ ] When an an instructor is sharing a video/survey, etc, he should select the course (not individual people) to share it with.
- [ ] Only the students that belong to those courses should see the items shared.

**Comment by KimberlyUvii** [comment]
Student receives notification to reply to instructor survey.

**Comment by miler350** [comment]
I've only seen that the admin panel section works. Please show me how a student joins a course.

**Comment by KimberlyUvii** [comment]
For now we can add students or instructors in the admin panel. 
Moving forward it should either be a dynamic login tethered to an API for Cuny or set up and dashboard with a key code will talk I have a call with IMS global remember we have a call with them next week as well
